MailPig.Web/Controllers/Api/EmailsController.cs
namespace MailPig.Web.Controllers.Api
{
    using BL.Mailing;
    using BL.Models;
    using BL.Services;
    using Core;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Http;

    [RoutePrefix("api/emails")]
    public class EmailsController : MailPigApiControllerBase
    {
        public EmailsService EmailsService { get; set; }

        public EmailsController()
        {
            EmailsService = new EmailsService(UnitOfWork);
        }

        // GET: api/emails
        [Route("")]
        public IEnumerable<EmailModel> Get()
        {
            return EmailsService.GetAllEmails();
        }

        // GET: api/emails/5
        [Route("{id}")]
        public EmailModel Get(int id)
        {
            return EmailsService.GetEmailById(id);
        }

        // POST: api/emails
        public IHttpActionResult Post([FromBody]EmailModel email)
        {
            EmailModel createdMail = EmailsService.CreateEmail(email);
            if (createdMail != null)
            {
                return Ok();
            }
            else
            {
                return BadRequest();
            }
        }

        // PUT: api/emails
        public IHttpActionResult Put([FromBody]EmailModel email)
        {
            EmailModel editedMail = EmailsService.EditEmail(email);
            if (editedMail != null)
            {
                return Ok();
            }
            else
            {
                return BadRequest();
            }
        }

        // POST api/emails/5/sendto/6
        [Route("{emailId}/sendto/{groupId}")]
        public IHttpActionResult SendEmailToGroup(int emailId, int groupId)
        {
            IEnumerable<MailerResult> results = EmailsService.SendMailToGroup(emailId, groupId);

            if (results.Any(result => result.Status != MailerResultStatusEnum.Succeeded))
            {
                return BadRequest();
            }
            return Ok();
        }
    }
}

MailPig.Web/Controllers/Api/GroupsController.cs
namespace MailPig.Web.Controllers.Api
{
    using BL.Models;
    using BL.Services;
    using Core;
    using System.Collections.Generic;
    using System.Web.Http;

    public class GroupsController : MailPigApiControllerBase
    {
        public GroupService GroupService { get; set; }

        public GroupsController()
        {
            GroupService = new GroupService(UnitOfWork);
        }

        // GET: api/Groups
        public IEnumerable<TableGroupModel> Get()
        {
            return GroupService.GetAllGroups();
        }

        // GET: api/Groups/5
        public GroupModel Get(int id)
        {
            return GroupService.GetGroupById(id);
        }

        // POST: api/Groups
        public IHttpActionResult Post([FromBody]GroupModel model)
        {
            GroupModel created = GroupService.CreateNewGroup(model);
            if (created != null)
            {
                return Ok();
            }
            else
            {
                return BadRequest();
            }
        }

        // PUT: api/Groups/5
        public IHttpActionResult Put(int id, [FromBody]GroupModel model)
        {
            GroupModel edited = GroupService.EditGroup(model);
            if (edited != null)
            {
                return Ok();
            }
            else
            {
                return BadRequest();
            }
        }

        // DELETE: api/Groups/5
        public IHttpActionResult Delete(int id)
        {
            bool removed = GroupService.RemoveGroup(id);
            if (removed)
            {
                return Ok();
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

MailPig.Web/Controllers/WelcomeController.cs
namespace MailPig.Web.Controllers
{
    using BL.Models;
    using BL.Services;
    using Core;
    using DAL.Core;
    using System.Web.Mvc;

    public class WelcomeController : MailPigControllerBase
    {
        public WelcomeController(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {
            StatisticsService = new StatisticsService(UnitOfWork);
        }

        public StatisticsService StatisticsService { get; set; }

        // GET: /
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Dashboard");
            }

            WelcomePageStatisticsModel model = StatisticsService.GetWelcomePageStatistics();
            return View(model);
        }

        // GET: Welcome/Description
        public ActionResult Description()
        {
            return View();
        }

        // GET: Welcome/References
        public ActionResult References()
        {
            return View();
        }

        // GET: Welcome/Try
        public ActionResult Try()
        {
            return View();
        }
    }
}

MailPig.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MailPig</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header>
        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MailPig", "Index", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                        <li>@Html.ActionLink("E-mailovi", "Index", "Emails")</li>
                        <li>@Html.ActionLink("Grupe", "Index", "Groups")</li>
                        <li>@Html.ActionLink("Pretplatnici", "Index", "Subscribers")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </header>

    <div class="container body-content">
        <main>
            @RenderBody()
        </main>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MailPig</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MailPig.Web/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greška - MailPig</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <main>
            @RenderBody()
        </main>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MailPig.Web/Views/Shared/_SubsriberRowEntry.cshtml
@model MailPig.BL.Models.SubscriberModel

<tr>
    @using (Html.BeginCollectionItem("Subscribers"))
    {
        @Html.HiddenFor(m => m.Id, new { @class = "row-identifier" })
        <td>
            @Model.Name
            @Html.HiddenFor(m => m.Name)
        </td>
        <td>
            @Model.Surname
            @Html.HiddenFor(m => m.Surname)
        </td>
        <td>
            @Model.Email
            @Html.HiddenFor(m => m.Email)
        </td>
        <td>
            <a class="pointy" onclick="removeSubscriber(this)" title="Obriši pretplatnika">
                <i class="glyphicon glyphicon-lg glyphicon-remove"></i>
            </a>
        </td>
    }
</tr>

MailPig.Web/Views/Shared/_WelcomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MailPig</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MailPig", "Index", "Welcome", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Zašto MailPig", "Description", "Welcome")</li>
                        <li>@Html.ActionLink("Reference", "References", "Welcome")</li>
                        <li>@Html.ActionLink("Isprobajte danas!", "Try", "Welcome")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </header>

    <div class="container body-content">
        <main>
            @RenderBody()
        </main>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MailPig</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>